CREATE TABLE IF NOT EXISTS SHOPPING_LIST_ITEMS (
    TYPE_ID  INTEGER NOT NULL,
    ITEM_NAME TEXT   NOT NULL,
    QUANTITY INTEGER NOT NULL DEFAULT 1,
    PRICE    REAL    NOT NULL DEFAULT 0,
    PRIMARY KEY (TYPE_ID)
);
