CREATE TABLE IF NOT EXISTS INVENTORY_CATEGORIES (
    groupID    INTEGER NOT NULL,
    groupName  TEXT    NOT NULL,
    categoryID INTEGER NOT NULL,
    PRIMARY KEY (groupID)
);

CREATE TABLE IF NOT EXISTS INVENTORY_TYPES (
    typeID      INTEGER NOT NULL,
    typeName    TEXT    NOT NULL,
    groupID     INTEGER NOT NULL,
    volume      REAL    NOT NULL DEFAULT 0,
    portionSize INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (typeID)
);

CREATE TABLE IF NOT EXISTS ITEM_LOOKUP (
    typeID       INTEGER NOT NULL,
    typeName     TEXT    NOT NULL,
    groupName    TEXT    NOT NULL,
    categoryName TEXT    NOT NULL,
    PRIMARY KEY (typeID)
);

CREATE TABLE IF NOT EXISTS REGIONS (
    regionID   INTEGER NOT NULL,
    regionName TEXT    NOT NULL,
    PRIMARY KEY (regionID)
);

CREATE TABLE IF NOT EXISTS SOLAR_SYSTEMS (
    solarSystemID   INTEGER NOT NULL,
    solarSystemName TEXT    NOT NULL,
    regionID        INTEGER NOT NULL,
    SECURITY        REAL    NOT NULL DEFAULT 0,
    PRIMARY KEY (solarSystemID)
);

CREATE TABLE IF NOT EXISTS STATIONS (
    STATION_ID      INTEGER NOT NULL,
    STATION_NAME    TEXT    NOT NULL,
    SOLAR_SYSTEM_ID INTEGER NOT NULL,
    regionID        INTEGER NOT NULL,
    PRIMARY KEY (STATION_ID)
);

CREATE TABLE IF NOT EXISTS INDUSTRY_ACTIVITIES (
    activityID   INTEGER NOT NULL,
    activityName TEXT    NOT NULL,
    PRIMARY KEY (activityID)
);

CREATE TABLE IF NOT EXISTS ALL_BLUEPRINTS_FACT (
    BLUEPRINT_ID           INTEGER NOT NULL,
    ITEM_ID                INTEGER NOT NULL,
    TECH_LEVEL             INTEGER NOT NULL DEFAULT 1,
    MAX_PRODUCTION_LIMIT   INTEGER NOT NULL DEFAULT 0,
    BASE_PRODUCTION_TIME   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (BLUEPRINT_ID)
);

CREATE TABLE IF NOT EXISTS ALL_BLUEPRINT_MATERIALS_FACT (
    BLUEPRINT_ID INTEGER NOT NULL,
    MATERIAL_ID  INTEGER NOT NULL,
    QUANTITY     INTEGER NOT NULL,
    ACTIVITY     INTEGER NOT NULL,
    PRIMARY KEY (BLUEPRINT_ID, MATERIAL_ID, ACTIVITY)
);

CREATE TABLE IF NOT EXISTS INDUSTRY_ACTIVITY_SKILLS (
    blueprintTypeID INTEGER NOT NULL,
    activityID      INTEGER NOT NULL,
    typeID          INTEGER NOT NULL,
    level           INTEGER NOT NULL,
    PRIMARY KEY (blueprintTypeID, activityID, typeID)
);