CREATE TABLE IF NOT EXISTS ESI_CHARACTER_DATA (
    CHARACTER_ID   INTEGER NOT NULL,
    CHARACTER_NAME TEXT    NOT NULL,
    CORPORATION_ID INTEGER NOT NULL,
    ALLIANCE_ID    INTEGER NULL,
    IS_DEFAULT     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (CHARACTER_ID)
);

CREATE TABLE IF NOT EXISTS CHARACTER_SKILLS (
    CHARACTER_ID         INTEGER NOT NULL,
    SKILL_TYPE_ID        INTEGER NOT NULL,
    SKILL_NAME           TEXT    NOT NULL,
    SKILL_POINTS         INTEGER NOT NULL DEFAULT 0,
    TRAINED_SKILL_LEVEL  INTEGER NOT NULL DEFAULT 0,
    ACTIVE_SKILL_LEVEL   INTEGER NOT NULL DEFAULT 0,
    OVERRIDE_SKILL       INTEGER NOT NULL DEFAULT 0,
    OVERRIDE_LEVEL       INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (CHARACTER_ID, SKILL_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS CHARACTER_STANDINGS (
    CHARACTER_ID INTEGER NOT NULL,
    NPC_TYPE_ID  INTEGER NOT NULL,
    NPC_TYPE     TEXT    NOT NULL,
    NPC_NAME     TEXT    NOT NULL,
    STANDING     REAL    NOT NULL,
    PRIMARY KEY (CHARACTER_ID, NPC_TYPE_ID, NPC_TYPE)
);

CREATE TABLE IF NOT EXISTS CURRENT_RESEARCH_AGENTS (
    CHARACTER_ID       INTEGER NOT NULL,
    AGENT_ID           INTEGER NOT NULL,
    SKILL_TYPE_ID      INTEGER NOT NULL,
    RP_PER_DAY         REAL    NOT NULL,
    RESEARCH_START_DATE TEXT   NOT NULL,
    REMAINDER_POINTS   REAL    NOT NULL,
    PRIMARY KEY (CHARACTER_ID, AGENT_ID)
);

CREATE TABLE IF NOT EXISTS RESEARCH_AGENTS (
    AGENT_ID    INTEGER NOT NULL,
    AGENT_NAME  TEXT    NOT NULL,
    RP_PER_DAY  REAL    NOT NULL DEFAULT 0,
    LEVEL       INTEGER NOT NULL DEFAULT 0,
    STATION     TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (AGENT_ID)
);

CREATE INDEX IF NOT EXISTS IX_CHARACTER_SKILLS_CHARACTER_ID
    ON CHARACTER_SKILLS (CHARACTER_ID);

CREATE INDEX IF NOT EXISTS IX_CHARACTER_STANDINGS_CHARACTER_ID
    ON CHARACTER_STANDINGS (CHARACTER_ID);

CREATE INDEX IF NOT EXISTS IX_CURRENT_RESEARCH_AGENTS_CHARACTER_ID
    ON CURRENT_RESEARCH_AGENTS (CHARACTER_ID);