CREATE TABLE IF NOT EXISTS ASSETS (
    ID          INTEGER NOT NULL,
    ItemID      INTEGER NOT NULL,
    LocationID  INTEGER NOT NULL DEFAULT 0,
    TypeID      INTEGER NOT NULL,
    Quantity    INTEGER NOT NULL DEFAULT 0,
    Flag        INTEGER NOT NULL DEFAULT 0,
    IsSingleton INTEGER NOT NULL DEFAULT 0,
    IsBPCopy    INTEGER NOT NULL DEFAULT 0,
    ItemName    TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (ID, ItemID)
);

CREATE INDEX IF NOT EXISTS IX_ASSETS_OWNER
    ON ASSETS (ID);