CREATE TABLE IF NOT EXISTS ESI_CORPORATION_CONNECTIONS (
    CORPORATION_ID          INTEGER NOT NULL,
    CORPORATION_NAME        TEXT    NOT NULL,
    AUTHORIZED_CHARACTER_ID INTEGER NOT NULL,
    HAS_ASSET_ACCESS        INTEGER NOT NULL DEFAULT 0,
    HAS_INDUSTRY_JOB_ACCESS INTEGER NOT NULL DEFAULT 0,
    HAS_BLUEPRINT_ACCESS    INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (CORPORATION_ID)
);

CREATE INDEX IF NOT EXISTS IX_ESI_CORPORATION_CONNECTIONS_AUTH_CHARACTER
    ON ESI_CORPORATION_CONNECTIONS (AUTHORIZED_CHARACTER_ID);