ALTER TABLE ESI_CORPORATION_CONNECTIONS
    ADD COLUMN HAS_DIRECTOR_ROLE INTEGER NOT NULL DEFAULT 0;

ALTER TABLE ESI_CORPORATION_CONNECTIONS
    ADD COLUMN HAS_FACTORY_MANAGER_ROLE INTEGER NOT NULL DEFAULT 0;

UPDATE ESI_CORPORATION_CONNECTIONS
SET HAS_DIRECTOR_ROLE = CASE
        WHEN HAS_ASSET_ACCESS = 1 OR HAS_BLUEPRINT_ACCESS = 1 THEN 1
        ELSE HAS_DIRECTOR_ROLE
    END,
    HAS_FACTORY_MANAGER_ROLE = CASE
        WHEN HAS_INDUSTRY_JOB_ACCESS = 1 THEN 1
        ELSE HAS_FACTORY_MANAGER_ROLE
    END;