CREATE TABLE IF NOT EXISTS OWNED_BLUEPRINTS (
    USER_ID        INTEGER NOT NULL,
    ITEM_ID        INTEGER NOT NULL,
    LOCATION_ID    INTEGER NOT NULL DEFAULT 0,
    BLUEPRINT_ID   INTEGER NOT NULL,
    BLUEPRINT_NAME TEXT    NOT NULL,
    QUANTITY       INTEGER NOT NULL DEFAULT 1,
    ME             INTEGER NOT NULL DEFAULT 0,
    TE             INTEGER NOT NULL DEFAULT 0,
    RUNS           INTEGER NOT NULL DEFAULT -1,
    BP_TYPE        INTEGER NOT NULL DEFAULT 1,
    OWNED          INTEGER NOT NULL DEFAULT 1,
    SCANNED        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (USER_ID, BLUEPRINT_ID)
);

CREATE INDEX IF NOT EXISTS IX_OWNED_BLUEPRINTS_USER_ID
    ON OWNED_BLUEPRINTS (USER_ID);